### ISSUE TITLE
[Steam Deck] Yuzu crashing after 10 mins of playing Cuphead

### ISSUE THREAD

**Issue by johnybutelkowiec** [flathub/org.yuzu_emu.yuzu#769] opened 2022-11-01 20:22 UTC
### yuzu Version

1219

### Description

Pretty much nothing important to add. The crash happens after approx. 8 mins both in desktop and game mode.

### Reproduction Certainty

Always

### System Information

```shell
Steam Deck 64 GB (with 512 GB sd card).
```

### Logs and Backtraces

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9913662/yuzu_log.txt)

### Remarks

Recently switched from flatpack to Appimage.

**Comment by liushuyu** [comment] 2022-11-27 01:17
Unfortunately, there is very little information included in your report and we can't determine the cause from the report alone.

Can you tell us if the AppImage version have the similar crash?

**Comment by liushuyu** [comment] 2022-12-29 01:33
Sorry, I have to close this issue due to OP being unresponsive. Please feel free to re-open it with more information (e.g. system information) and see if the latest version of yuzu has already fixed your problem.

**Closed by liushuyu** 2022-12-29 01:33 UTC
Labels: bug, invalid, steam deck
